### ISSUE TITLE
No such file or directory @ rb_sysopen - coverageinfo

### ISSUE THREAD

**Issue by lyon888** [erduoniba/hdcoverage#13]
你好，我按照你的教程作完之后，报下列的错误，请问下这种怎么解决呢

```
➜  CoverageResult git:(v7.21.0/lyon/login) ✗ ruby GitdiffUtils/diffParser.rb --diff-file=6af8866.diff --coverage-info-file=coverageinfo
======
coverage_info_path: .
coverage_info_file: coverageinfo
coverage_gather_file_path: ./coverageinfo_gather.info
======
coverage_gather_file: #<File:0x00007fc39f080e20>
GitdiffUtils/diffParser.rb:87:in `initialize': No such file or directory @ rb_sysopen - coverageinfo (Errno::ENOENT)
	from GitdiffUtils/diffParser.rb:87:in `open'
	from GitdiffUtils/diffParser.rb:87:in `gatherCoverageInfo'
	from GitdiffUtils/diffParser.rb:146:in `<main>'
```

**Comment by lyon888** [comment]
更正：我运行脚本后=>我运行项目后

**Comment by erduoniba** [comment]
看脚本你是用来生成增量代码覆盖率的。看报错是在打开 coverage_info_file 文件报错，提示不存在导致，这里需要你检查一下是否生成了 coverage_info_file 文件。
